// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package twins

import (
	"fmt"
	"github.com/panoratech/semva-cli/internal/client"
	"github.com/panoratech/semva-cli/internal/flagutil"
	"github.com/panoratech/semva-cli/internal/interactive"
	"github.com/panoratech/semva-cli/internal/output"
	"github.com/panoratech/semva-cli/internal/sdk/models/operations"
	"github.com/panoratech/semva-cli/internal/usage"
	"github.com/spf13/cobra"
)

var getTwinCmdMeta = []flagutil.FlagMeta{
	{FlagName: "twin-slug", Shorthand: "t", FieldPath: "TwinSlug", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initGetTwinCmd initializes the get-twin command.
func initGetTwinCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get",
		Short:   "Retrieve a twin",
		Long:    "Retrieve a twin",
		Example: "  semva twins get --twin-slug <value>",
		RunE:    runGetTwinCmd,
	}
	cmd.Flags().String("access-token", "", "Security credential")
	cmd.Flags().String("organization-api-key", "", "Security credential")
	flagutil.RegisterFlags(cmd, getTwinCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetTwinRequest](getTwinCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for get-twin: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetTwinCmd executes the get-twin command.
func runGetTwinCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	accessToken, _ := flagutil.GetStringFlag(cmd, "access-token")
	organizationAPIKey, _ := flagutil.GetStringFlag(cmd, "organization-api-key")
	var security operations.GetTwinSecurity
	if cmd.Flags().Changed("access-token") {
		security.AccessToken = &accessToken
	}
	if cmd.Flags().Changed("organization-api-key") {
		security.OrganizationAPIKey = &organizationAPIKey
	}
	if interactive.ShouldPrompt(cmd, getTwinCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, getTwinCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.GetTwinRequest](cmd, getTwinCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Twins.GetTwin(cmd.Context(), security, *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
