// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package twins

import (
	"fmt"
	"github.com/panoratech/semva-cli/internal/client"
	"github.com/panoratech/semva-cli/internal/flagutil"
	"github.com/panoratech/semva-cli/internal/interactive"
	"github.com/panoratech/semva-cli/internal/output"
	"github.com/panoratech/semva-cli/internal/sdk/models/operations"
	"github.com/panoratech/semva-cli/internal/usage"
	"github.com/spf13/cobra"
)

var listTwinsCmdMeta = []flagutil.FlagMeta{
	{FlagName: "page", Shorthand: "p", FieldPath: "Page", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, DefaultInt: 1, Description: "integer value"},
	{FlagName: "size", Shorthand: "s", FieldPath: "Size", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, DefaultInt: 50, Description: "integer value"},
}

// initListTwinsCmd initializes the list-twins command.
func initListTwinsCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list",
		Short:   "List available twins",
		Long:    "Returns the registered code twins ordered by display name.",
		Example: "  semva twins list",
		RunE:    runListTwinsCmd,
	}
	flagutil.RegisterFlags(cmd, listTwinsCmdMeta)
	if err := flagutil.ValidateMeta[operations.ListTwinsRequest](listTwinsCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for list-twins: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runListTwinsCmd executes the list-twins command.
func runListTwinsCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, listTwinsCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, listTwinsCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.ListTwinsRequest](cmd, listTwinsCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Twins.ListTwins(cmd.Context(), req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
