// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package twins

import (
	"github.com/panoratech/semva-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitTwinsRoot(parent *cobra.Command) error {
	var TwinsCmd = &cobra.Command{
		Use:   "twins",
		Short: "Browse the digital twins available for new sandboxes",
		Long:  "Browse the digital twins available for new sandboxes.",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initListTwinsCmd(TwinsCmd); err != nil {
		return err
	}

	if err := initGetTwinCmd(TwinsCmd); err != nil {
		return err
	}

	parent.AddCommand(TwinsCmd)
	return nil
}
