// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/models/components"
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
)

type AdvanceSandboxRequest struct {
	SandboxID     string                           `pathParam:"style=simple,explode=false,name=sandbox_id"`
	SandboxTwinID string                           `pathParam:"style=simple,explode=false,name=sandbox_twin_id"`
	Body          components.AdvanceSandboxRequest `request:"mediaType=application/json"`
}

func (a *AdvanceSandboxRequest) GetSandboxID() string {
	if a == nil {
		return ""
	}
	return a.SandboxID
}

func (a *AdvanceSandboxRequest) GetSandboxTwinID() string {
	if a == nil {
		return ""
	}
	return a.SandboxTwinID
}

func (a *AdvanceSandboxRequest) GetBody() components.AdvanceSandboxRequest {
	if a == nil {
		return components.AdvanceSandboxRequest{}
	}
	return a.Body
}

type AdvanceSandboxResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ResponseAdvanceSandbox map[string]int64
}

func (a AdvanceSandboxResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AdvanceSandboxResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AdvanceSandboxResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AdvanceSandboxResponse) GetResponseAdvanceSandbox() map[string]int64 {
	if a == nil {
		return nil
	}
	return a.ResponseAdvanceSandbox
}
