// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/semva-cli/internal/sdk/models/components"
	"github.com/panoratech/semva-cli/internal/sdk/sdkinternal/utils"
)

type CollectSandboxTwinCredentialSecurity struct {
	AccessToken        *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	OrganizationAPIKey *string `security:"scheme,type=apiKey,subtype=header,name=X-API-Key"`
}

func (c *CollectSandboxTwinCredentialSecurity) GetAccessToken() *string {
	if c == nil {
		return nil
	}
	return c.AccessToken
}

func (c *CollectSandboxTwinCredentialSecurity) GetOrganizationAPIKey() *string {
	if c == nil {
		return nil
	}
	return c.OrganizationAPIKey
}

type CollectSandboxTwinCredentialRequest struct {
	SandboxID     string `pathParam:"style=simple,explode=false,name=sandbox_id"`
	SandboxTwinID string `pathParam:"style=simple,explode=false,name=sandbox_twin_id"`
}

func (c *CollectSandboxTwinCredentialRequest) GetSandboxID() string {
	if c == nil {
		return ""
	}
	return c.SandboxID
}

func (c *CollectSandboxTwinCredentialRequest) GetSandboxTwinID() string {
	if c == nil {
		return ""
	}
	return c.SandboxTwinID
}

type CollectSandboxTwinCredentialResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	SandboxCredentialResponse *components.SandboxCredentialResponse
}

func (c CollectSandboxTwinCredentialResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CollectSandboxTwinCredentialResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CollectSandboxTwinCredentialResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CollectSandboxTwinCredentialResponse) GetSandboxCredentialResponse() *components.SandboxCredentialResponse {
	if c == nil {
		return nil
	}
	return c.SandboxCredentialResponse
}
