// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/semva-cli/internal/sdk/models/components"
	"github.com/panoratech/semva-cli/internal/sdk/sdkinternal/utils"
)

type CreateAPIKeySecurity struct {
	AccessToken        *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	OrganizationAPIKey *string `security:"scheme,type=apiKey,subtype=header,name=X-API-Key"`
}

func (c *CreateAPIKeySecurity) GetAccessToken() *string {
	if c == nil {
		return nil
	}
	return c.AccessToken
}

func (c *CreateAPIKeySecurity) GetOrganizationAPIKey() *string {
	if c == nil {
		return nil
	}
	return c.OrganizationAPIKey
}

type CreateAPIKeyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The new key, including its token
	CreatedAPIKeyResponse *components.CreatedAPIKeyResponse
}

func (c CreateAPIKeyResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateAPIKeyResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateAPIKeyResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateAPIKeyResponse) GetCreatedAPIKeyResponse() *components.CreatedAPIKeyResponse {
	if c == nil {
		return nil
	}
	return c.CreatedAPIKeyResponse
}
