// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/semva-cli/internal/sdk/models/components"
	"github.com/panoratech/semva-cli/internal/sdk/sdkinternal/utils"
)

type CreateSandboxResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	SandboxResponse *components.SandboxResponse
}

func (c CreateSandboxResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateSandboxResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateSandboxResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateSandboxResponse) GetSandboxResponse() *components.SandboxResponse {
	if c == nil {
		return nil
	}
	return c.SandboxResponse
}
