// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/semva-cli/internal/sdk/models/components"
	"github.com/panoratech/semva-cli/internal/sdk/sdkinternal/utils"
)

type CreateOrganizationSecurity struct {
	AccessToken        *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	OrganizationAPIKey *string `security:"scheme,type=apiKey,subtype=header,name=X-API-Key"`
}

func (c *CreateOrganizationSecurity) GetAccessToken() *string {
	if c == nil {
		return nil
	}
	return c.AccessToken
}

func (c *CreateOrganizationSecurity) GetOrganizationAPIKey() *string {
	if c == nil {
		return nil
	}
	return c.OrganizationAPIKey
}

type CreateOrganizationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The new organization and the caller's role in it
	MembershipResponse *components.MembershipResponse
}

func (c CreateOrganizationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateOrganizationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateOrganizationResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateOrganizationResponse) GetMembershipResponse() *components.MembershipResponse {
	if c == nil {
		return nil
	}
	return c.MembershipResponse
}
