// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/semva-cli/internal/sdk/models/components"
)

type DeleteSandboxTemplateSecurity struct {
	AccessToken        *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	OrganizationAPIKey *string `security:"scheme,type=apiKey,subtype=header,name=X-API-Key"`
}

func (d *DeleteSandboxTemplateSecurity) GetAccessToken() *string {
	if d == nil {
		return nil
	}
	return d.AccessToken
}

func (d *DeleteSandboxTemplateSecurity) GetOrganizationAPIKey() *string {
	if d == nil {
		return nil
	}
	return d.OrganizationAPIKey
}

type DeleteSandboxTemplateRequest struct {
	TemplateID string `pathParam:"style=simple,explode=false,name=template_id"`
}

func (d *DeleteSandboxTemplateRequest) GetTemplateID() string {
	if d == nil {
		return ""
	}
	return d.TemplateID
}

type DeleteSandboxTemplateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (d *DeleteSandboxTemplateResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}
