// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/semva-cli/internal/sdk/models/components"
	"github.com/panoratech/semva-cli/internal/sdk/sdkinternal/utils"
)

type EnsureDefaultOrganizationSecurity struct {
	AccessToken        *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	OrganizationAPIKey *string `security:"scheme,type=apiKey,subtype=header,name=X-API-Key"`
}

func (e *EnsureDefaultOrganizationSecurity) GetAccessToken() *string {
	if e == nil {
		return nil
	}
	return e.AccessToken
}

func (e *EnsureDefaultOrganizationSecurity) GetOrganizationAPIKey() *string {
	if e == nil {
		return nil
	}
	return e.OrganizationAPIKey
}

type EnsureDefaultOrganizationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The caller's organization and their role in it
	MembershipResponse *components.MembershipResponse
}

func (e EnsureDefaultOrganizationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EnsureDefaultOrganizationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EnsureDefaultOrganizationResponse) GetHTTPMeta() components.HTTPMetadata {
	if e == nil {
		return components.HTTPMetadata{}
	}
	return e.HTTPMeta
}

func (e *EnsureDefaultOrganizationResponse) GetMembershipResponse() *components.MembershipResponse {
	if e == nil {
		return nil
	}
	return e.MembershipResponse
}
