// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/semva-cli/internal/sdk/models/components"
	"github.com/panoratech/semva-cli/internal/sdk/sdkinternal/utils"
)

type GetSandboxRequest struct {
	SandboxID string `pathParam:"style=simple,explode=false,name=sandbox_id"`
}

func (g *GetSandboxRequest) GetSandboxID() string {
	if g == nil {
		return ""
	}
	return g.SandboxID
}

type GetSandboxResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	SandboxResponse *components.SandboxResponse
}

func (g GetSandboxResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetSandboxResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetSandboxResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetSandboxResponse) GetSandboxResponse() *components.SandboxResponse {
	if g == nil {
		return nil
	}
	return g.SandboxResponse
}
