// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/semva-cli/internal/sdk/models/components"
	"github.com/panoratech/semva-cli/internal/sdk/sdkinternal/utils"
)

type ListSandboxTemplatesSecurity struct {
	AccessToken        *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	OrganizationAPIKey *string `security:"scheme,type=apiKey,subtype=header,name=X-API-Key"`
}

func (l *ListSandboxTemplatesSecurity) GetAccessToken() *string {
	if l == nil {
		return nil
	}
	return l.AccessToken
}

func (l *ListSandboxTemplatesSecurity) GetOrganizationAPIKey() *string {
	if l == nil {
		return nil
	}
	return l.OrganizationAPIKey
}

type ListSandboxTemplatesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ResponseListSandboxTemplates []components.SandboxTemplateResponse
}

func (l ListSandboxTemplatesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListSandboxTemplatesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListSandboxTemplatesResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListSandboxTemplatesResponse) GetResponseListSandboxTemplates() []components.SandboxTemplateResponse {
	if l == nil {
		return nil
	}
	return l.ResponseListSandboxTemplates
}
