// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/semva-cli/internal/sdk/models/components"
	"github.com/panoratech/semva-cli/internal/sdk/sdkinternal/utils"
)

type ListTwinsRequest struct {
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	Size *int64 `default:"50" queryParam:"style=form,explode=true,name=size"`
}

func (l ListTwinsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListTwinsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListTwinsRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListTwinsRequest) GetSize() *int64 {
	if l == nil {
		return nil
	}
	return l.Size
}

type ListTwinsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PageTwinResponse *components.PageTwinResponse
}

func (l ListTwinsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListTwinsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListTwinsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListTwinsResponse) GetPageTwinResponse() *components.PageTwinResponse {
	if l == nil {
		return nil
	}
	return l.PageTwinResponse
}
