// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/semva-cli/internal/sdk/models/components"
	"github.com/panoratech/semva-cli/internal/sdk/sdkinternal/utils"
)

type ListSandboxesSecurity struct {
	AccessToken        *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	OrganizationAPIKey *string `security:"scheme,type=apiKey,subtype=header,name=X-API-Key"`
}

func (l *ListSandboxesSecurity) GetAccessToken() *string {
	if l == nil {
		return nil
	}
	return l.AccessToken
}

func (l *ListSandboxesSecurity) GetOrganizationAPIKey() *string {
	if l == nil {
		return nil
	}
	return l.OrganizationAPIKey
}

type ListSandboxesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ResponseListSandboxes []components.SandboxResponse
}

func (l ListSandboxesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListSandboxesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListSandboxesResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListSandboxesResponse) GetResponseListSandboxes() []components.SandboxResponse {
	if l == nil {
		return nil
	}
	return l.ResponseListSandboxes
}
