// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/semva-cli/internal/sdk/models/components"
	"github.com/panoratech/semva-cli/internal/sdk/optionalnullable"
	"github.com/panoratech/semva-cli/internal/sdk/sdkinternal/utils"
)

type ListRequestLogsRequest struct {
	SandboxID     string                                    `pathParam:"style=simple,explode=false,name=sandbox_id"`
	SandboxTwinID optionalnullable.OptionalNullable[string] `queryParam:"style=form,explode=true,name=sandbox_twin_id"`
	// Page number
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// Page size
	Size *int64 `default:"50" queryParam:"style=form,explode=true,name=size"`
}

func (l ListRequestLogsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListRequestLogsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListRequestLogsRequest) GetSandboxID() string {
	if l == nil {
		return ""
	}
	return l.SandboxID
}

func (l *ListRequestLogsRequest) GetSandboxTwinID() optionalnullable.OptionalNullable[string] {
	if l == nil {
		return nil
	}
	return l.SandboxTwinID
}

func (l *ListRequestLogsRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListRequestLogsRequest) GetSize() *int64 {
	if l == nil {
		return nil
	}
	return l.Size
}

type ListRequestLogsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PageRequestLogSummaryResponse *components.PageRequestLogSummaryResponse
}

func (l ListRequestLogsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListRequestLogsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListRequestLogsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListRequestLogsResponse) GetPageRequestLogSummaryResponse() *components.PageRequestLogSummaryResponse {
	if l == nil {
		return nil
	}
	return l.PageRequestLogSummaryResponse
}
