// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/semva-cli/internal/sdk/models/components"
	"github.com/panoratech/semva-cli/internal/sdk/sdkinternal/utils"
)

type ListSandboxRecordsSecurity struct {
	AccessToken        *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	OrganizationAPIKey *string `security:"scheme,type=apiKey,subtype=header,name=X-API-Key"`
}

func (l *ListSandboxRecordsSecurity) GetAccessToken() *string {
	if l == nil {
		return nil
	}
	return l.AccessToken
}

func (l *ListSandboxRecordsSecurity) GetOrganizationAPIKey() *string {
	if l == nil {
		return nil
	}
	return l.OrganizationAPIKey
}

type ListSandboxRecordsRequest struct {
	SandboxID     string `pathParam:"style=simple,explode=false,name=sandbox_id"`
	SandboxTwinID string `pathParam:"style=simple,explode=false,name=sandbox_twin_id"`
	Resource      string `pathParam:"style=simple,explode=false,name=resource"`
}

func (l *ListSandboxRecordsRequest) GetSandboxID() string {
	if l == nil {
		return ""
	}
	return l.SandboxID
}

func (l *ListSandboxRecordsRequest) GetSandboxTwinID() string {
	if l == nil {
		return ""
	}
	return l.SandboxTwinID
}

func (l *ListSandboxRecordsRequest) GetResource() string {
	if l == nil {
		return ""
	}
	return l.Resource
}

type ListSandboxRecordsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ResponseListSandboxRecords []components.SandboxRecordResponse
}

func (l ListSandboxRecordsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListSandboxRecordsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListSandboxRecordsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListSandboxRecordsResponse) GetResponseListSandboxRecords() []components.SandboxRecordResponse {
	if l == nil {
		return nil
	}
	return l.ResponseListSandboxRecords
}
