// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/semva-cli/internal/sdk/models/components"
	"github.com/panoratech/semva-cli/internal/sdk/sdkinternal/utils"
)

type ListOrganizationsSecurity struct {
	AccessToken        *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	OrganizationAPIKey *string `security:"scheme,type=apiKey,subtype=header,name=X-API-Key"`
}

func (l *ListOrganizationsSecurity) GetAccessToken() *string {
	if l == nil {
		return nil
	}
	return l.AccessToken
}

func (l *ListOrganizationsSecurity) GetOrganizationAPIKey() *string {
	if l == nil {
		return nil
	}
	return l.OrganizationAPIKey
}

type ListOrganizationsRequest struct {
	// Page number
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// Page size
	Size *int64 `default:"50" queryParam:"style=form,explode=true,name=size"`
}

func (l ListOrganizationsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListOrganizationsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListOrganizationsRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListOrganizationsRequest) GetSize() *int64 {
	if l == nil {
		return nil
	}
	return l.Size
}

type ListOrganizationsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// One page of the caller's memberships
	PageMembershipResponse *components.PageMembershipResponse
}

func (l ListOrganizationsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListOrganizationsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListOrganizationsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListOrganizationsResponse) GetPageMembershipResponse() *components.PageMembershipResponse {
	if l == nil {
		return nil
	}
	return l.PageMembershipResponse
}
