// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/semva-cli/internal/sdk/models/components"
	"github.com/panoratech/semva-cli/internal/sdk/sdkinternal/utils"
)

type ReadMeSecurity struct {
	AccessToken        *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	OrganizationAPIKey *string `security:"scheme,type=apiKey,subtype=header,name=X-API-Key"`
}

func (r *ReadMeSecurity) GetAccessToken() *string {
	if r == nil {
		return nil
	}
	return r.AccessToken
}

func (r *ReadMeSecurity) GetOrganizationAPIKey() *string {
	if r == nil {
		return nil
	}
	return r.OrganizationAPIKey
}

type ReadMeResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The caller and their memberships
	MeResponse *components.MeResponse
}

func (r ReadMeResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReadMeResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ReadMeResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *ReadMeResponse) GetMeResponse() *components.MeResponse {
	if r == nil {
		return nil
	}
	return r.MeResponse
}
