// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/semva-cli/internal/sdk/models/components"
	"github.com/panoratech/semva-cli/internal/sdk/sdkinternal/utils"
)

type ReadCurrentOrganizationSecurity struct {
	AccessToken        *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	OrganizationAPIKey *string `security:"scheme,type=apiKey,subtype=header,name=X-API-Key"`
}

func (r *ReadCurrentOrganizationSecurity) GetAccessToken() *string {
	if r == nil {
		return nil
	}
	return r.AccessToken
}

func (r *ReadCurrentOrganizationSecurity) GetOrganizationAPIKey() *string {
	if r == nil {
		return nil
	}
	return r.OrganizationAPIKey
}

type ReadCurrentOrganizationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The active organization and the caller's role in it
	MembershipResponse *components.MembershipResponse
}

func (r ReadCurrentOrganizationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReadCurrentOrganizationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ReadCurrentOrganizationResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *ReadCurrentOrganizationResponse) GetMembershipResponse() *components.MembershipResponse {
	if r == nil {
		return nil
	}
	return r.MembershipResponse
}
