// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/semva-cli/internal/sdk/models/components"
)

type RevokeAPIKeySecurity struct {
	AccessToken        *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	OrganizationAPIKey *string `security:"scheme,type=apiKey,subtype=header,name=X-API-Key"`
}

func (r *RevokeAPIKeySecurity) GetAccessToken() *string {
	if r == nil {
		return nil
	}
	return r.AccessToken
}

func (r *RevokeAPIKeySecurity) GetOrganizationAPIKey() *string {
	if r == nil {
		return nil
	}
	return r.OrganizationAPIKey
}

type RevokeAPIKeyRequest struct {
	APIKeyID string `pathParam:"style=simple,explode=false,name=api_key_id"`
}

func (r *RevokeAPIKeyRequest) GetAPIKeyID() string {
	if r == nil {
		return ""
	}
	return r.APIKeyID
}

type RevokeAPIKeyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (r *RevokeAPIKeyResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}
