// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/semva-cli/internal/sdk/models/components"
	"github.com/panoratech/semva-cli/internal/sdk/sdkinternal/utils"
)

type StartSandboxTwinRequest struct {
	SandboxID     string `pathParam:"style=simple,explode=false,name=sandbox_id"`
	SandboxTwinID string `pathParam:"style=simple,explode=false,name=sandbox_twin_id"`
}

func (s *StartSandboxTwinRequest) GetSandboxID() string {
	if s == nil {
		return ""
	}
	return s.SandboxID
}

func (s *StartSandboxTwinRequest) GetSandboxTwinID() string {
	if s == nil {
		return ""
	}
	return s.SandboxTwinID
}

type StartSandboxTwinResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	SandboxTwinResponse *components.SandboxTwinResponse
}

func (s StartSandboxTwinResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StartSandboxTwinResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StartSandboxTwinResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *StartSandboxTwinResponse) GetSandboxTwinResponse() *components.SandboxTwinResponse {
	if s == nil {
		return nil
	}
	return s.SandboxTwinResponse
}
