// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/semva-cli/internal/sdk/models/components"
	"github.com/panoratech/semva-cli/internal/sdk/sdkinternal/utils"
)

type StopSandboxTwinRequest struct {
	SandboxID     string `pathParam:"style=simple,explode=false,name=sandbox_id"`
	SandboxTwinID string `pathParam:"style=simple,explode=false,name=sandbox_twin_id"`
}

func (s *StopSandboxTwinRequest) GetSandboxID() string {
	if s == nil {
		return ""
	}
	return s.SandboxID
}

func (s *StopSandboxTwinRequest) GetSandboxTwinID() string {
	if s == nil {
		return ""
	}
	return s.SandboxTwinID
}

type StopSandboxTwinResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	SandboxTwinResponse *components.SandboxTwinResponse
}

func (s StopSandboxTwinResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StopSandboxTwinResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StopSandboxTwinResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *StopSandboxTwinResponse) GetSandboxTwinResponse() *components.SandboxTwinResponse {
	if s == nil {
		return nil
	}
	return s.SandboxTwinResponse
}
