// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/models/components"
	"github.com/panoratech/twinbay-cli/internal/sdk/sdkinternal/utils"
)

type UpdateSandboxRecordRequest struct {
	SandboxID     string                                `pathParam:"style=simple,explode=false,name=sandbox_id"`
	SandboxTwinID string                                `pathParam:"style=simple,explode=false,name=sandbox_twin_id"`
	Resource      string                                `pathParam:"style=simple,explode=false,name=resource"`
	ExternalID    string                                `pathParam:"style=simple,explode=false,name=external_id"`
	Body          components.UpdateSandboxRecordRequest `request:"mediaType=application/json"`
}

func (u *UpdateSandboxRecordRequest) GetSandboxID() string {
	if u == nil {
		return ""
	}
	return u.SandboxID
}

func (u *UpdateSandboxRecordRequest) GetSandboxTwinID() string {
	if u == nil {
		return ""
	}
	return u.SandboxTwinID
}

func (u *UpdateSandboxRecordRequest) GetResource() string {
	if u == nil {
		return ""
	}
	return u.Resource
}

func (u *UpdateSandboxRecordRequest) GetExternalID() string {
	if u == nil {
		return ""
	}
	return u.ExternalID
}

func (u *UpdateSandboxRecordRequest) GetBody() components.UpdateSandboxRecordRequest {
	if u == nil {
		return components.UpdateSandboxRecordRequest{}
	}
	return u.Body
}

type UpdateSandboxRecordResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	SandboxRecordResponse *components.SandboxRecordResponse
}

func (u UpdateSandboxRecordResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateSandboxRecordResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateSandboxRecordResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateSandboxRecordResponse) GetSandboxRecordResponse() *components.SandboxRecordResponse {
	if u == nil {
		return nil
	}
	return u.SandboxRecordResponse
}
