// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apikeys

import (
	"fmt"
	"github.com/panoratech/semva-cli/internal/client"
	"github.com/panoratech/semva-cli/internal/flagutil"
	"github.com/panoratech/semva-cli/internal/interactive"
	"github.com/panoratech/semva-cli/internal/output"
	"github.com/panoratech/semva-cli/internal/sdk/models/components"
	"github.com/panoratech/semva-cli/internal/sdk/models/operations"
	"github.com/panoratech/semva-cli/internal/usage"
	"github.com/spf13/cobra"
)

var createAPIKeyCmdMeta = []flagutil.FlagMeta{
	{FlagName: "name", Shorthand: "n", FieldPath: "Name", Kind: flagutil.FlagKindString, Required: true, Description: "What this key is for, in the operator's words [required]"},
	{FlagName: "expires-at", Shorthand: "e", FieldPath: "ExpiresAt", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"expires_at,omitempty"`, Description: "When the key stops working on its own. Omitted or null for a key that only stops when it is revoked."},
}

// initCreateApiKeyCmd initializes the create-api-key command.
func initCreateApiKeyCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "create",
		Short:   "Create an API key",
		Long:    "Mints a key for the active organization. It acts with the caller's role, read from their membership on every request, so it can never outrank them. The response is the only time the token is readable.",
		Example: "  semva api-keys create --name <value>",
		RunE:    runCreateApiKeyCmd,
	}
	flagutil.RegisterFlags(cmd, createAPIKeyCmdMeta)
	if err := flagutil.ValidateMeta[components.CreateAPIKeyRequest](createAPIKeyCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for create-api-key: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runCreateApiKeyCmd executes the create-api-key command.
func runCreateApiKeyCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, createAPIKeyCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, createAPIKeyCmdMeta); err != nil {
			return err
		}
	}
	request, err := flagutil.BuildRequest[components.CreateAPIKeyRequest](cmd, createAPIKeyCmdMeta, "", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.APIKeys.CreateAPIKey(cmd.Context(), *request, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
