// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apikeys

import (
	"fmt"
	"github.com/panoratech/semva-cli/internal/client"
	"github.com/panoratech/semva-cli/internal/flagutil"
	"github.com/panoratech/semva-cli/internal/interactive"
	"github.com/panoratech/semva-cli/internal/output"
	"github.com/panoratech/semva-cli/internal/sdk/models/operations"
	"github.com/panoratech/semva-cli/internal/usage"
	"github.com/spf13/cobra"
)

var listAPIKeysCmdMeta = []flagutil.FlagMeta{
	{FlagName: "page", Shorthand: "p", FieldPath: "Page", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, DefaultInt: 1, Description: "Page number"},
	{FlagName: "size", Shorthand: "s", FieldPath: "Size", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, DefaultInt: 50, Description: "Page size"},
}

// initListApiKeysCmd initializes the list-api-keys command.
func initListApiKeysCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list",
		Short:   "List API keys",
		Long:    "Every key of the active organization that has not been revoked, oldest first. A key that has expired is still listed, so that it can be read and cleaned up rather than vanishing unexplained; `expires_at` says which. Tokens are never included. Paginated: walk the pages with `page` and `size`.",
		Example: "  semva api-keys list",
		RunE:    runListApiKeysCmd,
	}
	flagutil.RegisterFlags(cmd, listAPIKeysCmdMeta)
	if err := flagutil.ValidateMeta[operations.ListAPIKeysRequest](listAPIKeysCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for list-api-keys: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runListApiKeysCmd executes the list-api-keys command.
func runListApiKeysCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, listAPIKeysCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, listAPIKeysCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.ListAPIKeysRequest](cmd, listAPIKeysCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.APIKeys.ListAPIKeys(cmd.Context(), req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
