// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apikeys

import (
	"fmt"
	"github.com/panoratech/semva-cli/internal/client"
	"github.com/panoratech/semva-cli/internal/flagutil"
	"github.com/panoratech/semva-cli/internal/interactive"
	"github.com/panoratech/semva-cli/internal/output"
	"github.com/panoratech/semva-cli/internal/sdk"
	"github.com/panoratech/semva-cli/internal/sdk/models/operations"
	"github.com/panoratech/semva-cli/internal/usage"
	"github.com/spf13/cobra"
)

var revokeAPIKeyCmdMeta = []flagutil.FlagMeta{
	{FlagName: "api-key-id", Shorthand: "a", FieldPath: "APIKeyID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initRevokeApiKeyCmd initializes the revoke-api-key command.
func initRevokeApiKeyCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "revoke",
		Short:   "Revoke an API key",
		Long:    "The key stops working immediately. Its row stays, so a key seen in a log can still be named, and its token can never be minted again.",
		Example: "  semva api-keys revoke --api-key-id 70d05b12-db01-4e93-afb7-c26ecf254345",
		RunE:    runRevokeApiKeyCmd,
	}
	flagutil.RegisterFlags(cmd, revokeAPIKeyCmdMeta)
	if err := flagutil.ValidateMeta[operations.RevokeAPIKeyRequest](revokeAPIKeyCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for revoke-api-key: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runRevokeApiKeyCmd executes the revoke-api-key command.
func runRevokeApiKeyCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, revokeAPIKeyCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, revokeAPIKeyCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.RevokeAPIKeyRequest](cmd, revokeAPIKeyCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.APIKeys.RevokeAPIKey(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
