// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package logs

import (
	"fmt"
	"github.com/panoratech/semva-cli/internal/client"
	"github.com/panoratech/semva-cli/internal/flagutil"
	"github.com/panoratech/semva-cli/internal/interactive"
	"github.com/panoratech/semva-cli/internal/output"
	"github.com/panoratech/semva-cli/internal/sdk"
	"github.com/panoratech/semva-cli/internal/sdk/models/operations"
	"github.com/panoratech/semva-cli/internal/usage"
	"github.com/spf13/cobra"
)

var getCmdMeta = []flagutil.FlagMeta{
	{FlagName: "sandbox-id", Shorthand: "s", FieldPath: "SandboxID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "request-id", Shorthand: "r", FieldPath: "RequestID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initGetCmd initializes the get command.
func initGetCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get",
		Short:   "Retrieve a sandbox request log",
		Long:    "Retrieve a sandbox request log",
		Example: "  semva logs get --sandbox-id a0fac35a-bd5d-41d3-a59e-2da4c1e8a360 --request-id 2fd11644-623b-4542-adf8-08c8674cb288",
		RunE:    runGetCmd,
	}
	flagutil.RegisterFlags(cmd, getCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetRequestLogRequest](getCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for get: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetCmd executes the get command.
func runGetCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, getCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, getCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.GetRequestLogRequest](cmd, getCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Sandboxes.Logs.Get(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
