// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package organizations

import (
	"fmt"
	"github.com/panoratech/semva-cli/internal/client"
	"github.com/panoratech/semva-cli/internal/flagutil"
	"github.com/panoratech/semva-cli/internal/interactive"
	"github.com/panoratech/semva-cli/internal/output"
	"github.com/panoratech/semva-cli/internal/sdk/models/components"
	"github.com/panoratech/semva-cli/internal/sdk/models/operations"
	"github.com/panoratech/semva-cli/internal/usage"
	"github.com/spf13/cobra"
)

var createOrganizationCmdMeta = []flagutil.FlagMeta{
	{FlagName: "name", Shorthand: "n", FieldPath: "Name", Kind: flagutil.FlagKindString, Required: true, Description: "Display name of the new organization [required]"},
}

// initCreateOrganizationCmd initializes the create-organization command.
func initCreateOrganizationCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "create",
		Short:   "Create an organization",
		Long:    "Creates the organization in WorkOS with the caller as an admin, then mirrors it locally. The caller's current token is unchanged; refresh the AuthKit session into the new organization to act inside it.",
		Example: "  semva organizations create --name <value>",
		RunE:    runCreateOrganizationCmd,
	}
	cmd.Flags().String("access-token", "", "Security credential")
	cmd.Flags().String("organization-api-key", "", "Security credential")
	flagutil.RegisterFlags(cmd, createOrganizationCmdMeta)
	if err := flagutil.ValidateMeta[components.CreateOrganizationRequest](createOrganizationCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for create-organization: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runCreateOrganizationCmd executes the create-organization command.
func runCreateOrganizationCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	accessToken, _ := flagutil.GetStringFlag(cmd, "access-token")
	organizationAPIKey, _ := flagutil.GetStringFlag(cmd, "organization-api-key")
	var security operations.CreateOrganizationSecurity
	if cmd.Flags().Changed("access-token") {
		security.AccessToken = &accessToken
	}
	if cmd.Flags().Changed("organization-api-key") {
		security.OrganizationAPIKey = &organizationAPIKey
	}
	if interactive.ShouldPrompt(cmd, createOrganizationCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, createOrganizationCmdMeta); err != nil {
			return err
		}
	}
	request, err := flagutil.BuildRequest[components.CreateOrganizationRequest](cmd, createOrganizationCmdMeta, "", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Organizations.CreateOrganization(cmd.Context(), security, *request, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
