// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package organizations

import (
	"fmt"
	"github.com/panoratech/semva-cli/internal/client"
	"github.com/panoratech/semva-cli/internal/flagutil"
	"github.com/panoratech/semva-cli/internal/interactive"
	"github.com/panoratech/semva-cli/internal/output"
	"github.com/panoratech/semva-cli/internal/sdk/models/operations"
	"github.com/panoratech/semva-cli/internal/usage"
	"github.com/spf13/cobra"
)

var listOrganizationsCmdMeta = []flagutil.FlagMeta{
	{FlagName: "page", Shorthand: "p", FieldPath: "Page", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, DefaultInt: 1, Description: "Page number"},
	{FlagName: "size", Shorthand: "s", FieldPath: "Size", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, DefaultInt: 50, Description: "Page size"},
}

// initListOrganizationsCmd initializes the list-organizations command.
func initListOrganizationsCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list",
		Short:   "List your organizations",
		Long:    "Every organization the caller is a member of, with their role in each, oldest membership first. Independent of the organization the current token acts in. Paginated: walk the pages with `page` and `size`.",
		Example: "  semva organizations list",
		RunE:    runListOrganizationsCmd,
	}
	cmd.Flags().String("access-token", "", "Security credential")
	cmd.Flags().String("organization-api-key", "", "Security credential")
	flagutil.RegisterFlags(cmd, listOrganizationsCmdMeta)
	if err := flagutil.ValidateMeta[operations.ListOrganizationsRequest](listOrganizationsCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for list-organizations: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runListOrganizationsCmd executes the list-organizations command.
func runListOrganizationsCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	accessToken, _ := flagutil.GetStringFlag(cmd, "access-token")
	organizationAPIKey, _ := flagutil.GetStringFlag(cmd, "organization-api-key")
	var security operations.ListOrganizationsSecurity
	if cmd.Flags().Changed("access-token") {
		security.AccessToken = &accessToken
	}
	if cmd.Flags().Changed("organization-api-key") {
		security.OrganizationAPIKey = &organizationAPIKey
	}
	if interactive.ShouldPrompt(cmd, listOrganizationsCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, listOrganizationsCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.ListOrganizationsRequest](cmd, listOrganizationsCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Organizations.ListOrganizations(cmd.Context(), security, req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
