// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package organizations

import (
	"fmt"
	"github.com/panoratech/semva-cli/internal/client"
	"github.com/panoratech/semva-cli/internal/flagutil"
	"github.com/panoratech/semva-cli/internal/interactive"
	"github.com/panoratech/semva-cli/internal/output"
	"github.com/panoratech/semva-cli/internal/sdk"
	"github.com/panoratech/semva-cli/internal/sdk/models/components"
	"github.com/panoratech/semva-cli/internal/sdk/models/operations"
	"github.com/panoratech/semva-cli/internal/usage"
	"github.com/spf13/cobra"
)

var renameCurrentOrganizationCmdMeta = []flagutil.FlagMeta{
	{FlagName: "name", Shorthand: "n", FieldPath: "Name", Kind: flagutil.FlagKindString, Required: true, Description: "New display name of the organization [required]"},
}

// initRenameCurrentOrganizationCmd initializes the rename-current-organization command.
func initRenameCurrentOrganizationCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "rename-current",
		Short:   "Rename the active organization",
		Long:    "Requires the **admin** role or above in the active organization.",
		Example: "  semva organizations rename-current --name <value>",
		RunE:    runRenameCurrentOrganizationCmd,
		Aliases: []string{"rcu"},
	}
	flagutil.RegisterFlags(cmd, renameCurrentOrganizationCmdMeta)
	if err := flagutil.ValidateMeta[components.UpdateOrganizationRequest](renameCurrentOrganizationCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for rename-current-organization: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runRenameCurrentOrganizationCmd executes the rename-current-organization command.
func runRenameCurrentOrganizationCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, renameCurrentOrganizationCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, renameCurrentOrganizationCmdMeta); err != nil {
			return err
		}
	}
	request, err := flagutil.BuildRequest[components.UpdateOrganizationRequest](cmd, renameCurrentOrganizationCmdMeta, "", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Organizations.RenameCurrentOrganization(cmd.Context(), *request, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
