// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package records

import (
	"github.com/panoratech/semva-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitRecordsRoot(parent *cobra.Command) error {
	var RecordsCmd = &cobra.Command{
		Use:   "records",
		Short: "Operations for records",
		Long:  "Operations for records",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initListCmd(RecordsCmd); err != nil {
		return err
	}

	if err := initUpdateCmd(RecordsCmd); err != nil {
		return err
	}

	parent.AddCommand(RecordsCmd)
	return nil
}
