// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sandboxes

import (
	"fmt"
	"github.com/panoratech/semva-cli/internal/client"
	"github.com/panoratech/semva-cli/internal/flagutil"
	"github.com/panoratech/semva-cli/internal/interactive"
	"github.com/panoratech/semva-cli/internal/output"
	"github.com/panoratech/semva-cli/internal/sdk"
	"github.com/panoratech/semva-cli/internal/sdk/models/operations"
	"github.com/panoratech/semva-cli/internal/usage"
	"github.com/spf13/cobra"
)

var getCmdMeta = []flagutil.FlagMeta{
	{FlagName: "sandbox-id", Shorthand: "s", FieldPath: "SandboxID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initGetCmd initializes the get command.
func initGetCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get",
		Short:   "Retrieve a sandbox",
		Long:    "Retrieve a sandbox",
		Example: "  semva sandboxes get --sandbox-id 713e9030-8ff2-45e6-aedb-61e8e9aa4c2f",
		RunE:    runGetCmd,
	}
	flagutil.RegisterFlags(cmd, getCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetSandboxRequest](getCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for get: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetCmd executes the get command.
func runGetCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, getCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, getCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.GetSandboxRequest](cmd, getCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Sandboxes.Get(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
