// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sandboxes

import (
	"github.com/panoratech/semva-cli/internal/client"
	"github.com/panoratech/semva-cli/internal/flagutil"
	"github.com/panoratech/semva-cli/internal/output"
	"github.com/panoratech/semva-cli/internal/sdk/models/operations"
	"github.com/panoratech/semva-cli/internal/usage"
	"github.com/spf13/cobra"
)

// initListCmd initializes the list command.
func initListCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list",
		Short:   "List sandboxes",
		Long:    "List sandboxes",
		Example: "  semva sandboxes list",
		RunE:    runListCmd,
	}
	cmd.Flags().String("access-token", "", "Security credential")
	cmd.Flags().String("organization-api-key", "", "Security credential")
	parent.AddCommand(cmd)
	return nil
}

// runListCmd executes the list command.
func runListCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	accessToken, _ := flagutil.GetStringFlag(cmd, "access-token")
	organizationAPIKey, _ := flagutil.GetStringFlag(cmd, "organization-api-key")
	var security operations.ListSandboxesSecurity
	if cmd.Flags().Changed("access-token") {
		security.AccessToken = &accessToken
	}
	if cmd.Flags().Changed("organization-api-key") {
		security.OrganizationAPIKey = &organizationAPIKey
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Sandboxes.List(cmd.Context(), security, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
