// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package templates

import (
	"github.com/panoratech/semva-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitTemplatesRoot(parent *cobra.Command) error {
	var TemplatesCmd = &cobra.Command{
		Use:   "templates",
		Short: "Operations for templates",
		Long:  "Operations for templates",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initListCmd(TemplatesCmd); err != nil {
		return err
	}

	if err := initDeleteCmd(TemplatesCmd); err != nil {
		return err
	}

	parent.AddCommand(TemplatesCmd)
	return nil
}
