// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package healthchecks

import (
	"github.com/panoratech/semva-cli/internal/client"
	"github.com/panoratech/semva-cli/internal/output"
	"github.com/panoratech/semva-cli/internal/sdk/models/operations"
	"github.com/panoratech/semva-cli/internal/usage"
	"github.com/spf13/cobra"
)

// initReadHealthCmd initializes the read-health command.
func initReadHealthCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "read-health",
		Short:   "Read Health",
		Long:    "Read Health",
		Example: "  semva healthchecks read-health",
		RunE:    runReadHealthCmd,
		Aliases: []string{"rh"},
	}
	parent.AddCommand(cmd)
	return nil
}

// runReadHealthCmd executes the read-health command.
func runReadHealthCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Healthchecks.ReadHealth(cmd.Context(), sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
