// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package healthchecks

import (
	"github.com/panoratech/semva-cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitHealthchecksRoot(parent *cobra.Command) error {
	var HealthchecksCmd = &cobra.Command{
		Use:   "healthchecks",
		Short: "Healthcheck endpoints",
		Long:  "Healthcheck endpoints",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initReadRootCmd(HealthchecksCmd); err != nil {
		return err
	}

	if err := initReadHealthCmd(HealthchecksCmd); err != nil {
		return err
	}

	parent.AddCommand(HealthchecksCmd)
	return nil
}
