workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Twinbay:
        inputs:
            - location: https://api.twinbay.ai/openapi.json
        overlays:
            - location: ./.speakeasy/api-key-only.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/panora-technologies-inc/twinbay/twinbay
targets:
    twinbay:
        target: cli
        source: Twinbay
