// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sandboxestwins

import (
	"fmt"
	"github.com/panoratech/semva-cli/internal/client"
	"github.com/panoratech/semva-cli/internal/flagutil"
	"github.com/panoratech/semva-cli/internal/interactive"
	"github.com/panoratech/semva-cli/internal/output"
	"github.com/panoratech/semva-cli/internal/sdk/models/operations"
	"github.com/panoratech/semva-cli/internal/usage"
	"github.com/spf13/cobra"
)

var advanceCmdMeta = []flagutil.FlagMeta{
	{FlagName: "sandbox-id", FieldPath: "SandboxID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "sandbox-twin-id", FieldPath: "SandboxTwinID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "at", Shorthand: "a", FieldPath: "Body.At", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"at,omitempty"`, Description: "Instant to advance the sandbox to. Defaults to now."},
}

// initAdvanceCmd initializes the advance command.
func initAdvanceCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "advance",
		Short:   "Advance a deterministic twin lifecycle",
		Long:    "Advance a deterministic twin lifecycle",
		Example: "  semva sandboxes-twins advance --sandbox-id 0e5430b8-577a-40fb-a158-9fc5ad75ab04 --sandbox-twin-id 10a63cd8-60d5-4c91-bbd5-7c17aa12a3d7",
		RunE:    runAdvanceCmd,
	}
	flagutil.RegisterFlags(cmd, advanceCmdMeta)
	if err := flagutil.ValidateMeta[operations.AdvanceSandboxRequest](advanceCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for advance: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runAdvanceCmd executes the advance command.
func runAdvanceCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, advanceCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, advanceCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.AdvanceSandboxRequest](cmd, advanceCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Sandboxes.Twins.Advance(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
