// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/panoratech/semva-cli/internal/sdk/optionalnullable"
	"github.com/panoratech/semva-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type AdvanceSandboxRequest struct {
	// Instant to advance the sandbox to. Defaults to now.
	At optionalnullable.OptionalNullable[time.Time] `json:"at,omitzero"`
}

func (a AdvanceSandboxRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AdvanceSandboxRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AdvanceSandboxRequest) GetAt() optionalnullable.OptionalNullable[time.Time] {
	if a == nil {
		return nil
	}
	return a.At
}
