// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/panoratech/semva-cli/internal/sdk/optionalnullable"
	"github.com/panoratech/semva-cli/internal/sdk/sdkinternal/utils"
)

type CreateSandboxRequest struct {
	// Display name of the new sandbox
	Name string `json:"name"`
	// A natural-language description of the scenario the whole sandbox represents. Every twin in it is seeded from this description while it is being provisioned.
	Prompt optionalnullable.OptionalNullable[string] `json:"prompt,omitzero"`
	// Provider twins to provision in the sandbox. Omitted when the sandbox is started from a template, which holds them already.
	Twins optionalnullable.OptionalNullable[[]CreateSandboxTwinRequest] `json:"twins,omitzero"`
	// A saved sandbox definition to start from, instead of listing twins. Its twins, their curated scenarios and their instructions are used as they were saved.
	Template optionalnullable.OptionalNullable[string] `json:"template,omitzero"`
	// Also save this sandbox's definition, so another sandbox can be started from it later.
	SaveAsTemplate *bool `default:"false" json:"save_as_template"`
}

func (c CreateSandboxRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateSandboxRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateSandboxRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateSandboxRequest) GetPrompt() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.Prompt
}

func (c *CreateSandboxRequest) GetTwins() optionalnullable.OptionalNullable[[]CreateSandboxTwinRequest] {
	if c == nil {
		return nil
	}
	return c.Twins
}

func (c *CreateSandboxRequest) GetTemplate() optionalnullable.OptionalNullable[string] {
	if c == nil {
		return nil
	}
	return c.Template
}

func (c *CreateSandboxRequest) GetSaveAsTemplate() *bool {
	if c == nil {
		return nil
	}
	return c.SaveAsTemplate
}
