// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateOrganizationRequest struct {
	// Display name of the new organization
	Name string `json:"name"`
}

func (c *CreateOrganizationRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}
