// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SandboxCredentialResponse - The provider key a container minted, handed over exactly once.
type SandboxCredentialResponse struct {
	APIKey string `json:"api_key"`
}

func (s *SandboxCredentialResponse) GetAPIKey() string {
	if s == nil {
		return ""
	}
	return s.APIKey
}
