// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/panoratech/semva-cli/internal/sdk/optionalnullable"
	"github.com/panoratech/semva-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type SandboxResponse struct {
	ID        string                                       `json:"id"`
	Slug      string                                       `json:"slug"`
	Name      string                                       `json:"name"`
	Status    string                                       `json:"status"`
	Twins     []SandboxTwinResponse                        `json:"twins"`
	CreatedAt time.Time                                    `json:"created_at"`
	ExpiresAt optionalnullable.OptionalNullable[time.Time] `json:"expires_at,omitzero"`
}

func (s SandboxResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SandboxResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SandboxResponse) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SandboxResponse) GetSlug() string {
	if s == nil {
		return ""
	}
	return s.Slug
}

func (s *SandboxResponse) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *SandboxResponse) GetStatus() string {
	if s == nil {
		return ""
	}
	return s.Status
}

func (s *SandboxResponse) GetTwins() []SandboxTwinResponse {
	if s == nil {
		return []SandboxTwinResponse{}
	}
	return s.Twins
}

func (s *SandboxResponse) GetCreatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.CreatedAt
}

func (s *SandboxResponse) GetExpiresAt() optionalnullable.OptionalNullable[time.Time] {
	if s == nil {
		return nil
	}
	return s.ExpiresAt
}
