// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/panoratech/semva-cli/internal/sdk/optionalnullable"
	"github.com/panoratech/semva-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type SandboxTemplateResponse struct {
	ID        string                                    `json:"id"`
	Name      string                                    `json:"name"`
	Prompt    optionalnullable.OptionalNullable[string] `json:"prompt,omitzero"`
	Twins     []SandboxTemplateTwinResponse             `json:"twins"`
	CreatedAt time.Time                                 `json:"created_at"`
}

func (s SandboxTemplateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SandboxTemplateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SandboxTemplateResponse) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SandboxTemplateResponse) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *SandboxTemplateResponse) GetPrompt() optionalnullable.OptionalNullable[string] {
	if s == nil {
		return nil
	}
	return s.Prompt
}

func (s *SandboxTemplateResponse) GetTwins() []SandboxTemplateTwinResponse {
	if s == nil {
		return []SandboxTemplateTwinResponse{}
	}
	return s.Twins
}

func (s *SandboxTemplateResponse) GetCreatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.CreatedAt
}
