// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/panoratech/semva-cli/internal/sdk/optionalnullable"
	"github.com/panoratech/semva-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type SandboxTwinResponse struct {
	ID       string `json:"id"`
	TwinSlug string `json:"twin_slug"`
	// The release the current container was started from.
	TwinVersion optionalnullable.OptionalNullable[string] `json:"twin_version,omitzero"`
	// running or stopped
	DesiredState string `json:"desired_state"`
	// What the twin is actually doing: pending, provisioning, starting, ready, stopping, stopped or failed.
	State string `json:"state"`
	URL   string `json:"url"`
	// Why the current run is not serving, if it is not.
	Failure   optionalnullable.OptionalNullable[string]    `json:"failure,omitzero"`
	CreatedAt time.Time                                    `json:"created_at"`
	ReadyAt   optionalnullable.OptionalNullable[time.Time] `json:"ready_at,omitzero"`
}

func (s SandboxTwinResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SandboxTwinResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SandboxTwinResponse) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *SandboxTwinResponse) GetTwinSlug() string {
	if s == nil {
		return ""
	}
	return s.TwinSlug
}

func (s *SandboxTwinResponse) GetTwinVersion() optionalnullable.OptionalNullable[string] {
	if s == nil {
		return nil
	}
	return s.TwinVersion
}

func (s *SandboxTwinResponse) GetDesiredState() string {
	if s == nil {
		return ""
	}
	return s.DesiredState
}

func (s *SandboxTwinResponse) GetState() string {
	if s == nil {
		return ""
	}
	return s.State
}

func (s *SandboxTwinResponse) GetURL() string {
	if s == nil {
		return ""
	}
	return s.URL
}

func (s *SandboxTwinResponse) GetFailure() optionalnullable.OptionalNullable[string] {
	if s == nil {
		return nil
	}
	return s.Failure
}

func (s *SandboxTwinResponse) GetCreatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.CreatedAt
}

func (s *SandboxTwinResponse) GetReadyAt() optionalnullable.OptionalNullable[time.Time] {
	if s == nil {
		return nil
	}
	return s.ReadyAt
}
