// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/panoratech/twinbay-cli/internal/sdk/optionalnullable"
)

// SandboxTemplateTwinResponse - A slot a template asks for, named as a create request names it.
type SandboxTemplateTwinResponse struct {
	Twin             string                                    `json:"twin"`
	ScenarioTemplate optionalnullable.OptionalNullable[string] `json:"scenario_template,omitzero"`
	Prompt           optionalnullable.OptionalNullable[string] `json:"prompt,omitzero"`
}

func (s *SandboxTemplateTwinResponse) GetTwin() string {
	if s == nil {
		return ""
	}
	return s.Twin
}

func (s *SandboxTemplateTwinResponse) GetScenarioTemplate() optionalnullable.OptionalNullable[string] {
	if s == nil {
		return nil
	}
	return s.ScenarioTemplate
}

func (s *SandboxTemplateTwinResponse) GetPrompt() optionalnullable.OptionalNullable[string] {
	if s == nil {
		return nil
	}
	return s.Prompt
}
