// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SandboxRecordResponse struct {
	ExternalID string         `json:"external_id"`
	Resource   string         `json:"resource"`
	Body       map[string]any `json:"body"`
}

func (s *SandboxRecordResponse) GetExternalID() string {
	if s == nil {
		return ""
	}
	return s.ExternalID
}

func (s *SandboxRecordResponse) GetResource() string {
	if s == nil {
		return ""
	}
	return s.Resource
}

func (s *SandboxRecordResponse) GetBody() map[string]any {
	if s == nil {
		return map[string]any{}
	}
	return s.Body
}
