// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ScenarioResponse struct {
	Slug        string `json:"slug"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (s *ScenarioResponse) GetSlug() string {
	if s == nil {
		return ""
	}
	return s.Slug
}

func (s *ScenarioResponse) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *ScenarioResponse) GetDescription() string {
	if s == nil {
		return ""
	}
	return s.Description
}
