// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Security struct {
	AccessToken *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

func (s *Security) GetAccessToken() *string {
	if s == nil {
		return nil
	}
	return s.AccessToken
}
