// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TwinResponse struct {
	Slug        string             `json:"slug"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Version     string             `json:"version"`
	Scenarios   []ScenarioResponse `json:"scenarios"`
}

func (t *TwinResponse) GetSlug() string {
	if t == nil {
		return ""
	}
	return t.Slug
}

func (t *TwinResponse) GetName() string {
	if t == nil {
		return ""
	}
	return t.Name
}

func (t *TwinResponse) GetDescription() string {
	if t == nil {
		return ""
	}
	return t.Description
}

func (t *TwinResponse) GetVersion() string {
	if t == nil {
		return ""
	}
	return t.Version
}

func (t *TwinResponse) GetScenarios() []ScenarioResponse {
	if t == nil {
		return []ScenarioResponse{}
	}
	return t.Scenarios
}
