// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdateOrganizationRequest struct {
	// New display name of the organization
	Name string `json:"name"`
}

func (u *UpdateOrganizationRequest) GetName() string {
	if u == nil {
		return ""
	}
	return u.Name
}
