// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdateSandboxRecordRequest struct {
	Body map[string]any `json:"body"`
}

func (u *UpdateSandboxRecordRequest) GetBody() map[string]any {
	if u == nil {
		return map[string]any{}
	}
	return u.Body
}
